<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PatientMedicalData extends Model
{
    use HasFactory;

    //use HasUuids;

    protected $table = 'PatientMedicalData';
    protected $primaryKey = 'PatientId';
    protected $incrementing = false;
    protected $keyType = 'int';
    protected $connection = 'pgsql';
    protected $fillable = [
        'PatientId',
        'Created',
        'Updated',
        'Deleted',
        'EntranceDate',
        'EntranceComment',
        'DepartuerDate',
        'Complaints',
        'AnamnesisMorbi',
        'AnamnesisVitae',
        'ChamberId',
        'Allergoanamnez',
        'SickLeave',
        'Employment',
        'TransfusionsAnamnesis',
        'PerRectum',
        'EntranceSurvey',
        'PrimaryDiagnosis',
        'AdditionalDiagnosis',
        'TreatmentPlan',
        'PrimaryAnalysis',
        'OperationType',
        'DischargedDate',
        'EntranceConclusion',
        'EntranceAssign',
        'BloodType',
        'ClinicalDiagnosis',
        'PGI',
        'CostReference',
        'DischargeComment',
        'DischargeWorkingCapacity',
        'DepartmentId',
        'PreoperativeInspection',
        'ECG',
        'UrineStab',
        'VID',
        'DischargeConclusion',
        'DischargeState',
        'DischargeRecomendations',
        'TreponemaPallidum',
        'XRay',
        'TransferIntoAnotherDepartment',
        'OperationPostAppointment',
        'DepartmentHeadConclusion',
        'DepartmentHeadComment',
        'ConclusionDoctor',
        'ConclusionDate',
        'ConclusionGoal',
        'HighTechMedicalCare',
        'EntranceFilledDate',
        'DischargeConclusionComment',
        'Intoxication',
        'Oncology',
        'EntranceSurveyInstrumental',
        'DepartmentHeadDiagnosis',
        'DischargeComplaints',
        'OncoConsulationGoal',
        'HBsag',
        'RW',
        'AntiHCV',
        'Weigth',
        'Heigth',
        'PathoanatomicalArrivalDate',
        'PathoanatomicalRegisteredDate',
        'PathoanatomicalConclusion',
        'PathoanatomicalComment',
        'PathoanatomicalMacroscopicDesc',
        'PathoanatomicalMicroscopicDesc',
        'PathoanatomicalColoring',
        'PathoanatomicalMaterialInSolution',
        'PathoanatomicalMaterialDirty',
        'PathoanatomicalSafetyOfPacking',
        'PathoanatomicalResearchDate',
        'DepartmentHeadInspectedDate',
        'DischargeResult',
        'CurrentYearHospitalization',
        'HospitalizationInterval',
        'EntranceInjury',
        'EntranceDiagnosis',
        'RedirectingNumber',
        'RedirectingDate',
        'EntranceOrganization',
        'EntranceNumber',
        'EntranceOrderNumber',
        'TherapistId',
        'AddressLocality',
        'BloodTransfusionAntibodies',
        'BloodTransfusionCompletedDate',
        'BloodTransfusionContainer',
        'BloodTransfusionDate',
        'BloodTransfusionEnv',
        'BloodTransfusionIndividual',
        'BloodTransfusionPast',
        'BloodTransfusionReactions',
        'BloodTransfusionReadings',
        'BloodTransfusionRhesus',
        'BloodTransfusionStartedDate',
        'GradualEpicrisisComment',
        'RedirectionOrganization',
        'Education',
        'FamilyStatus',
        'Occupation',
        '[Privileges]',
        'SocialStatus',
        'DischargeCheckupLogDate',
        'StLocalis',
        'OncoConclusionDate',
        'RedirectionDoctor',
        'EntranceSkinDiseases',
        'MedicalCardSpecialNotes',
        'MedicalExpertiseConclusion',
        'MedicalExpertiseSentAt',
        'OtherTreatmentTypes',
        'PrehospitalDefects',
        'EntranceIllnessCount',
        'EntranceIllnessEmergencyIndications',
        'EntranceIllnessEmergencyIndicationsHours',
        'EntranceIllnessFirstTime',
        'EntranceIllnessPlannedOrder',
        'MedicalCardDischarge',
        'MedicalCardDischargeOtherHospital',
    ];
}
